# Select image from https://hub.docker.com/_/php/
image: php:7.0

stages:
  - Test

# Select what we should cache
cache:
  paths:
    - vendor/

before_script:
  # Install git and unzip (composer will need them)
  - apt-get update && apt-get install -qqy git unzip zlib1g-dev
  # install php extensions
  - docker-php-ext-install zip
#  - docker-php-ext-install openssl
  # Install composer
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  # Install all project dependencies
  - composer install
  # Run webserver
  - php -S localhost:8134 &>/dev/null&

# Test
test:
  services:
    - name: selenium/standalone-chrome:3.141.59-oxygen
      alias: selenium

  stage: Test
  script:
    - LOCAL_IP=$HOSTNAME
    - echo Local IP $LOCAL_IP
    - sed -i "s/localhost:8134/$LOCAL_IP:8134/" tests/acceptance.suite.yml
    - sed -i "s/host:\ localhost/host:\ 127.0.0.1/" tests/acceptance.suite.yml
    - vendor/bin/codecept run